[package]
name = "numerilib"
version = "0.1.0"
authors = ["vedang"]
edition = "2021"
license-file = "LICENSE"
description = "A Rust Mathematics Library"
readme = "CratesREADME.md"
repository = "https://github.com/VLambda/ferrate.git"

[dependencies]

[dev-dependencies]
assert_approx_eq = "1.1.0"