[package]
name = "mathematica"
version = "0.0.5"
authors = ["vedang"]
edition = "2021"
license-file = "LICENSE"
description = "A Rust Math Library"
readme = "CratesREADME.md"
repository = "https://github.com/VLambda/ferrate.git"

[dependencies]

[dev-dependencies]
assert_approx_eq = "1.1.0"