[package]
name = "vml"
version = "0.0.1"
authors = ["vedang"]
edition = "2021"
license-file = "LICENSE"
description = "Vedang's Math Library"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
